sudo: false
language: java
dist: bionic

branches:
  except:
    - /^tmp\/.*/
    - /^REL.*/

stages:
  - name: test
    if: not branch =~ ^release\/.*$
  - name: release
    # releases pgjdbc for Java 8
    # It does set release tag and update pom.xml versions
    if: branch =~ ^release\/.*$
  - name: release_prev
    # releases pgjdbc for Java 6, Java 7
    # pgjdbc-jreX requires release pom.xml versions of the main project, so pgjdbc-jreX should be
    # released after the release of the main version, thus second stage
    if: branch =~ ^release\/.*$

before_script:
  #- test $(grep "after_n_builds" codecov.yml | tr -d '[:space:]' | cut -d":" -f2) -eq $(grep -e "COVERAGE=Y$" .travis.yml | wc -l) || exit 1
  - export PG_DATADIR="/etc/postgresql/${PG_VERSION}/main"
  - export PG_SLAVE1_DATADIR="/etc/postgresql/${PG_VERSION}/slave1"
  - export PG_SLAVE2_DATADIR="/etc/postgresql/${PG_VERSION}/slave2"
  - bash -x ./.travis/travis_install_postgres.sh
  - test "x$XA" == 'x' || bash -x ./.travis/travis_configure_xa.sh
  - test "x$REPLICATION" == 'x' || bash -x ./.travis/travis_configure_replication.sh
  - test "x$SSLTEST" == 'x' || bash -x ./.travis/travis_configure_ssl.sh
  - bash -x ./.travis/travis_start_postgres.sh
  - test "x$PG_VERSION" != 'xHEAD' || psql -U postgres -c "set password_encryption='scram-sha-256'; create user test with password 'test';"
  - test "x$PG_VERSION" = 'xHEAD' || psql -U postgres -c "create user test with password 'test';"
  - test "x$REPLICATION" == 'x' || psql -U postgres -c "alter user test with replication;"
  - psql -c 'create database test owner test;' -U postgres
  - test "x$SSLTEST" == 'x' || bash -x ./.travis/travis_ssl_users.sh
  - test "x$REPLICATION" == 'x' || bash -x ./.travis/travis_create_slaves.sh
  - if [[ $TRAVIS_BRANCH == release/* ]]; then echo "MAVEN_OPTS='-Xmx1g'" > ~/.mavenrc; else echo "MAVEN_OPTS='-Xmx1g -Dgpg.skip=true'" > ~/.mavenrc; fi
  - test "x$PG_VERSION" == 'x' || test "x$NO_HSTORE" == 'xY' || psql test -c 'CREATE EXTENSION hstore;' -U postgres
  - test "x$PG_VERSION" == 'x' || test "x$CREATE_PLPGSQL" == 'x' || createlang -U postgres plpgsql test
  - test "x$PG_VERSION" == 'x' || test "x$PLPGSQL_EXTENSION" == 'x' || psql test -c 'CREATE EXTENSION IF NOT EXISTS plpgsql;' -U postgres

env:
  global:
    - secure: "NI+aqwRLLVt2feJdk/2ZEZnsaPyu+vOx8MahVxjz0UUVvRHVqxM5O1M0R53NJfEeIjflOzgZJwRLqgyl6dkdfjytRhaHWGptQdehV4cwNb+4epnn8WlpRzMac65zTQqnbGVtw9jissDQv6/Zl/+D+DMcU65BbFZkix40whILXG0="

before_install:
  - bash -x ./.travis/travis_install_zulu.sh
  - test -z "${ZULU_JDK}" || export JDK${ZULU_JDK}_HOME=/usr/lib/jvm/zulu-${ZULU_JDK}-amd64
  - unset _JAVA_OPTIONS # see https://github.com/travis-ci/travis-ci/issues/8408

script:
  - if [[ $TRAVIS_CPU_ARCH =~ arm64* ]]; then wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh ; chmod +x ./install-jdk.sh ; export JAVA_HOME=$(./install-jdk.sh -o linux-aarch64 --feature $JDK -e | tail -1) ; export PATH=$PATH:$JAVA_HOME/bin; java --version ;fi
  # make sure previous build artifacts are not used for subsequent builds
  - rm -rf $HOME/.m2/repository/org/postgresql || true
  - test -d "${JDK8_HOME}" || export JDK8_HOME=$(jdk_switcher home oraclejdk8)
  - test -d "${JDK14_HOME}" || export JDK14_HOME=$(jdk_switcher home oraclejdk14)
  - test ${JDK} -eq 7 || jdk_switcher use oraclejdk8 # Run Gradle with Java 8, build with Toolchains.
  - test -z "${ZULU_JDK}" || export TRAVIS_JDK_VERSION=zulujdk${ZULU_JDK} # trick codecov to use correct jdk version
  - if [[ $TRAVIS_BRANCH == release/* ]]; then bash -x .travis/travis_release.sh; else bash -x ./.travis/travis_build.sh; fi
  - bash -x ./.travis/travis_check_postgres_health.sh
  # To avoid useless S3 cache updates (https://github.com/travis-ci/travis-ci/issues/1441#issuecomment-67607074)
  #- mkdir /tmp/cache-trick
  #- mv $HOME/.m2/repository/org/postgresql /tmp/cache-trick/

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
  # No sense in caching current build artifacts
  - rm -rf $HOME/.m2/repository/org/postgresql

# Skip default "mvn install" issued by Travis
# Root project cannot be compiled with older JDKs, so it makes sense to just skip the step
install: true

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

matrix:
  fast_finish: true
  include:
    - stage: test
      env:
        - FEDORA_CI=Y
      services:
        - docker
      if: type != pull_request
    - jdk: openjdk-ea
      sudo: required
      addons:
        postgresql: "10"
      env:
        - PG_VERSION=10
        - JDK=12
        - TZ=America/New_York # flips between −05:00 and −04:00
        - BUILD_SCAN=Y
    - jdk: openjdk-ea
      sudo: required
      addons:
        postgresql: "11"
      env:
        - PG_VERSION=11
        - XA=true
        - COVERAGE=Y
        - NO_HSTORE=Y
        - PLPGSQL_EXTENSION=Y
    - stage: test
      arch: arm64-graviton2
      virt: lxd
      group: edge
      env:
        - FEDORA_CI=Y
      services:
        - docker
      if: type != pull_request
    - jdk: openjdk-ea
      arch: arm64-graviton2
      virt: lxd
      group: edge
      sudo: required
      addons:
        postgresql: "13"
      env:
        - PG_VERSION=13
        - JDK=15
        - TZ=America/New_York # flips between −05:00 and −04:00
        - BUILD_SCAN=Y
        - MVN_CUSTOM_ARGS="-PfailOnJavadocWarning=false"

# Deploy snapshots to Maven Central
after_success:
  - "test $TRAVIS_PULL_REQUEST == 'false' && test $TRAVIS_BRANCH == 'master' && test $MCENTRAL == 'Y' && ./.travis/travis_deploy.sh"
