name: Seed build cache

on:
  push:
    branches:
      - '*'

jobs:
  ubuntu-code-style:
    strategy:
      matrix:
          arch: [aarch64, x86]
          os: [ubuntu, macos, windows]
          jdk: [8, 11]

    name: '${{ matrix.arch }}, ${{ matrix.os }}, ${{ matrix.jdk }} seed build cache'
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: uraimo/run-on-arch-action@v2.0.5
        with:
          arch: ${{ matrix.arch }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: 'Set up JDK ${{ matrix.jdk }}'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: burrunan/gradle-cache-action@v1
        name: Build pgjdbc
        env:
          S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
          S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
        with:
          job-id: jdk${{ matrix.jdk }}
          arguments: build -x test --scan -i
