name: Seed build cache

on:
  push:
    branches:
      - '*'

jobs:
  ubuntu-code-style:
    strategy:
      matrix:
        os: [ubuntu]
        jdk: [8, 11]

    name: '${{ matrix.os }}, ${{ matrix.jdk }} seed build cache'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: 'Set up JDK ${{ matrix.jdk }}'
        uses: bzhaoopenstack/setup-java@v9
        with:
          java-version: ${{ matrix.jdk }}
          architecture: aarch64
      - uses: burrunan/gradle-cache-action@v1
        name: Build pgjdbc
        env:
          S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
          S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
        with:
          job-id: jdk${{ matrix.jdk }}
          arguments: build -x test --scan -i
